// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjawlpzilvdkaxptijpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqYXdscHppbHZka2F4cHRpanBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTE3NTIsImV4cCI6MjA2MjQ4Nzc1Mn0.5yMmvsuUk9dAcfJ0RbQ57FnJJ7RYDmLglr-ND3eGuUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);